Config = {
    __LicenseKey = "",

    middlewares = {
        ban_player = function(playerId --[[ number ]], reason --[[ string (like "honeypot_event_triggered", etc..) ]])
            print(playerId .. " got banned by the anticheat for the following reason: " .. reason);
            -- exports['myVeryGoodBanSystem']:banPlayer(playerId);
        end,

        kick_player = function(playerId --[[ number ]], reason --[[ string (like "honeypot_event_triggered", etc..) ]])
            DropPlayer(playerId, reason);
        end,
    },

    webhooks = { -- { [key: string]: string | string[] }
        ['webhook_for_events'] = "https://www.discord.com/...", 
        ['webhook_for_requests'] = { "https://www.discord.com/serverhook1", "https://www.discord.com/serverhook2" },
    },

    requests = {
        mode = "blacklist", -- "disabled" | "blacklist" | "whitelist"
        log_all_request = true, -- boolean

        whitelisted_urls = { -- string[]
            "github.com", 
            "discord.com", 
            "discord.gg"
        },

        blacklisted_urls = { -- string[]
            "cipher-panel.xyz",
            "cipher-panel.me", 
        },
    },

    events = {
        -- put `shared_script "@cobain_pink/shared/imports/Events.lua"` in the top of the fxmanifest.lua or __resource.lua to use this feature in the desired resource.
        tunnel = {
            mode = "shared_secret", -- "shared_secret" | "time" | "disabled"
            
            shared_secret = {
                type = "random", -- "random" | "specified"
                
                -- generated secret length (only width type "random")
                length = 16,

                -- specified code to generate unique random eventnames to communicate between client and server
                -- secret_code = "idkwhyiaddedthistbhjustuserandomlol", 
            },

            time = {
                eventhandler_regen_interval = 800, -- ms
                fallback_event_amount = 3, 
            },
        },

        validator = {
            enabled = true,

            list = {
                --[[
                    [key: string]: {
                        limit?: {
                            interval: number;
                            amount: number; -- the max amount of event triggers from clients in ~interval~ seconds

                            webhook: Webhook | nil;
                            penalty_on_exceeding: "kick" | "ban" | nil; 
                        };

                        position?: {
                            max_distance: number, 
                            coord: Vector3;

                            webhook: Webhook | nil;
                            penalty_on_exceeding: "kick" | "ban" | nil; 
                        };
                    }
                ]]

                ['esx_illegal_drugs:startHarvestWeed'] = {
                    interval = 5000,
                    limit = 3, 

                    position = {
                        max_distance = 12, 
                        coord = vector3(0, 0, 0)
                    },
                },
            },
        },
    },

    heartbeat = {
        timeout_penalty = "", -- "ban" | "kick" | nil
        timeout_tolerance = 30, -- number (seconds)
    },

    explosions = {
        mode = "blacklist", -- "blacklist" | "whitelist" | "disabled" | nil

        spam_protection = {
            mode = "kick", -- "kick" | "ban" | "disabled" | nil 

            interval = 60, -- seconds
            limit = 3, -- total limit in the specified interval, otherwise the player will be banned.
        },

        default_behavior = {
            ban = false,
            log = true, 
            webhook = "",
        },

        -- When mode is set to "blacklist", the specified explosions will be filtered and canceled, any other explision type will be synced to clients.
        -- With mode set to "whitelist", the only specified explosions will be synced to clients, otherwise it gets canceled and "default_behavior" will be used.
        -- With mode "disabled", this feature will be disabled obviously lol
        list = {
            [0] = { id = "Grenade", behavior = { ban = true, log = true } },
            [1] = { id = "GrenadeLauncher", behavior = { ban = true, log = true } },
            [2] = { id = "Molotov", behavior = { ban = true, log = true } },
            [3] = { id = "Rocket", behavior = { ban = false, log = true } },
            [4] = { id = "TankShell", behavior = { ban = false, log = true } },
            [5] = { id = "Hi_Octane", behavior = { ban = false, log = true } },
            [6] = { id = "Car", behavior = { ban = false, log = true } },
            [7] = { id = "Plance", behavior = { ban = false, log = true } },
            [8] = { id = "PetrolPump", behavior = { ban = false, log = true } },
            [9] = { id = "Bike", behavior = { ban = false, log = true } },
            [10] = { id = "Dir_Steam", behavior = { ban = false, log = true } },
            [11] = { id = "Dir_Flame", behavior = { ban = false, log = true } },
            [12] = { id = "Dir_Water_Hydrant", behavior = { ban = false, log = true } },
            [13] = { id = "Dir_Gas_Canister", behavior = { ban = false, log = true } },
            [14] = { id = "Boat", behavior = { ban = false, log = true } },
            [15] = { id = "Ship_Destroy", behavior = { ban = false, log = true } },
            [16] = { id = "Truck", behavior = { ban = false, log = true } },
            [17] = { id = "Bullet", behavior = { ban = false, log = true } },
            [18] = { id = "SmokeGrenadeLauncher", behavior = { ban = true, log = true } },
            [19] = { id = "SmokeGrenade", behavior = { ban = false, log = true } },
            [20] = { id = "BZGAS", behavior = { ban = false, log = true } },
            [21] = { id = "Flare", behavior = { ban = false, log = true } },
            [22] = { id = "Gas_Canister", behavior = { ban = false, log = true } },
            [23] = { id = "Extinguisher", behavior = { ban = false, log = true } },
            [24] = { id = "Programmablear", behavior = { ban = false, log = nil } },
            [25] = { id = "Train", behavior = { ban = false, log = true } },
            [26] = { id = "Barrel", behavior = { ban = false, log = true } },
            [27] = { id = "PROPANE", behavior = { ban = false, log = true } },
            [28] = { id = "Blimp", behavior = { ban = false, log = true } },
            [29] = { id = "Dir_Flame_Explode", behavior = { ban = false, log = true } },
            [30] = { id = "Tanker", behavior = { ban = false, log = true } },
            [31] = { id = "PlaneRocket", behavior = { ban = false, log = true } },
            [32] = { id = "VehicleBullet", behavior = { ban = false, log = nil } },
            [33] = { id = "Gas_Tank", behavior = { ban = false, log = true } },
            [34] = { id = "FireWork", behavior = { ban = false, log = true } },
            [35] = { id = "SnowBall", behavior = { ban = false, log = true } },
            [36] = { id = "ProxMine", behavior = { ban = true, log = true } },
            [37] = { id = "Valkyrie_Cannon", behavior = { ban = true, log = true } }
        },
    },

    entities = {
        mode = "blacklist", -- "blacklist" | "whitelist" | "disabled" | nil 
        
        behavior = {
            ban_on_sync = true, 
            webhook = "", -- WebhookId | nil
        },

        list = { -- { [key: Hash | string]: boolean }
            [GetHashKey("rhino")] = true,
            [GetHashKey("policeb")] = true,
            [GetHashKey("cargobob2")] = true,
            [GetHashKey("cargobob3")] = true,
            [GetHashKey("cargobob4")] = true,
            [GetHashKey("cargobob")] = true,
            [GetHashKey("hunter")] = true,
            [GetHashKey("avenger2")] = true,
            [GetHashKey("cargoplane")] = true,
            [GetHashKey("cerberus2")] = true,
            [GetHashKey("cerberus")] = true,
            [GetHashKey("phantom2")] = true,
            [GetHashKey("issi6")] = true,
            [GetHashKey("annihilator")] = true,
            [GetHashKey("akula")] = true,
            [GetHashKey("frogger2")] = true,
            [GetHashKey("savage")] = true,
            [GetHashKey("skylift")] = true,
            [GetHashKey("valkyrie")] = true,
            [GetHashKey("valkyrie2")] = true,
            [GetHashKey("annihilator2")] = true,
            [GetHashKey("cutter")] = true,
            [GetHashKey("dump")] = true,
            [GetHashKey("handler")] = true,
            [GetHashKey("oppressor")] = true,
            [GetHashKey("oppressor2")] = true,
            [GetHashKey("slamvan6")] = true,
            [GetHashKey("blazer5")] = true,
            [GetHashKey("bruiser")] = true,
            [GetHashKey("bruiser2")] = true,
            [GetHashKey("bruiser3")] = true,
            [GetHashKey("brutus3")] = true,
            [GetHashKey("brutus2")] = true,
            [GetHashKey("brutus")] = true,
            [GetHashKey("dune2")] = true,
            [GetHashKey("dune4")] = true,
            [GetHashKey("dune5")] = true,
            [GetHashKey("insurgent3")] = true,
            [GetHashKey("insurgent")] = true,
            [GetHashKey("menacer")] = true,
            [GetHashKey("buzzard")] = true,
            [GetHashKey("nightshark")] = true,
            [GetHashKey("rcbandito")] = true,
            [GetHashKey("technical")] = true,
            [GetHashKey("technical2")] = true,
            [GetHashKey("technical3")] = true,
            [GetHashKey("avenger")] = true,
            [GetHashKey("lazer")] = true,
            [GetHashKey("blimp")] = true,
            [GetHashKey("blimp2")] = true,
            [GetHashKey("blimp3")] = true,
            [GetHashKey("bombushka")] = true,
            [GetHashKey("hydra")] = true,
            [GetHashKey("jet")] = true,
            [GetHashKey("molotok")] = true,
            [GetHashKey("mogul")] = true,
            [GetHashKey("nokota")] = true,
            [GetHashKey("pyro")] = true,
            [GetHashKey("rogue")] = true,
            [GetHashKey("starling")] = true,
            [GetHashKey("strikeforce")] = true,
            [GetHashKey("titan")] = true,
            [GetHashKey("tula")] = true,
            [GetHashKey("volatol")] = true,
            [GetHashKey("tourbus")] = true,
            [GetHashKey("zr3803")] = true,
            [GetHashKey("zr3802")] = true,
            [GetHashKey("zr380")] = true,
            [GetHashKey("armytrailer2")] = true,
            [GetHashKey("docktug")] = true,
            [GetHashKey("ripley")] = true,
            [GetHashKey("cerberus3")] = true,
            [GetHashKey("apc")] = true,
            [GetHashKey("barracks")] = true,
            [GetHashKey("barracks2")] = true,
            [GetHashKey("barracks3")] = true,
            [GetHashKey("barrage")] = true,
            [GetHashKey("chernobog")] = true,
            [GetHashKey("halftrack")] = true,
            [GetHashKey("khanjali")] = true,
            [GetHashKey("minitank")] = true,
            [GetHashKey("scarab")] = true,
            [GetHashKey("scarab2")] = true,
            [GetHashKey("scarab3")] = true,
            [GetHashKey("thruster")] = true,
            [GetHashKey("trailersmall2")] = true,
            [GetHashKey("firetruck")] = true,
            [GetHashKey("besra")] = true,
            [GetHashKey("submersible")] = true,
            [GetHashKey("stockade")] = true,
            [GetHashKey("ambulance")] = true,
            [GetHashKey("stockade3")] = true,
            [GetHashKey("blimp")] = true,
            [GetHashKey("blimp2")] = true,
            [GetHashKey("blimp3")] = true,
            [GetHashKey("taco")] = true,
            [GetHashKey("prop_fnclink_05crnr1")] = true,
            [GetHashKey("xs_prop_hamburgher_wl")] = true,
            [GetHashKey("xs_prop_plastic_bottle_wl")] = true,
            [GetHashKey("prop_windmill_01")] = true,
            [GetHashKey("p_spinning_anus_s")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
            [GetHashKey("stt_prop_ramp_adj_hloop")] = true,
            [GetHashKey("stt_prop_ramp_adj_loop")] = true,
            [GetHashKey("stt_prop_ramp_jump_l")] = true,
            [GetHashKey("stt_prop_ramp_jump_m")] = true,
            [GetHashKey("stt_prop_ramp_jump_s")] = true,
            [GetHashKey("stt_prop_ramp_jump_xl")] = true,
            [GetHashKey("stt_prop_ramp_jump_xs")] = true,
            [GetHashKey("stt_prop_ramp_jump_xxl")] = true,
            [GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
            [GetHashKey("stt_prop_ramp_spiral_m")] = true,
            [GetHashKey("stt_prop_ramp_spiral_s")] = true,
            [GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
            [GetHashKey("prop_beach_fire")] = true,
            [GetHashKey("prop_rock_1_a")] = true,
            [GetHashKey("prop_rock_1_b")] = true,
            [GetHashKey("prop_rock_1_c")] = true,
            [GetHashKey("prop_rock_1_d")] = true,
            [GetHashKey("prop_player_gasmask")] = true,
            [GetHashKey("prop_rock_1_e")] = true,
            [GetHashKey("prop_rock_1_f")] = true,
            [GetHashKey("prop_rock_1_g")] = true,
            [GetHashKey("prop_rock_1_h")] = true,
            [GetHashKey("prop_test_boulder_01")] = true,
            [GetHashKey("prop_test_boulder_02")] = true,
            [GetHashKey("prop_test_boulder_03")] = true,
            [GetHashKey("prop_test_boulder_04")] = true,
            [GetHashKey("apa_mp_apa_crashed_usaf_01a")] = true,
            [GetHashKey("ex_prop_exec_crashdp")] = true,
            [GetHashKey("apa_mp_apa_yacht_o1_rail_a")] = true,
            [GetHashKey("apa_mp_apa_yacht_o1_rail_b")] = true,
            [GetHashKey("apa_mp_h_yacht_armchair_01")] = true,
            [GetHashKey("apa_mp_h_yacht_armchair_03")] = true,
            [GetHashKey("apa_mp_h_yacht_armchair_04")] = true,
            [GetHashKey("apa_mp_h_yacht_barstool_01")] = true,
            [GetHashKey("apa_mp_h_yacht_bed_01")] = true,
            [GetHashKey("apa_mp_h_yacht_bed_02")] = true,
            [GetHashKey("apa_mp_h_yacht_coffee_table_01")] = true,
            [GetHashKey("apa_mp_h_yacht_coffee_table_02")] = true,
            [GetHashKey("apa_mp_h_yacht_floor_lamp_01")] = true,
            [GetHashKey("apa_mp_h_yacht_side_table_01")] = true,
            [GetHashKey("apa_mp_h_yacht_side_table_02")] = true,
            [GetHashKey("apa_mp_h_yacht_sofa_01")] = true,
            [GetHashKey("apa_mp_h_yacht_sofa_02")] = true,
            [GetHashKey("apa_mp_h_yacht_stool_01")] = true,
            [GetHashKey("apa_mp_h_yacht_strip_chair_01")] = true,
            [GetHashKey("apa_mp_h_yacht_table_lamp_01")] = true,
            [GetHashKey("apa_mp_h_yacht_table_lamp_02")] = true,
            [GetHashKey("apa_mp_h_yacht_table_lamp_03")] = true,
            [GetHashKey("prop_flag_columbia")] = true,
            [GetHashKey("apa_mp_apa_yacht_o2_rail_a")] = true,
            [GetHashKey("apa_mp_apa_yacht_o2_rail_b")] = true,
            [GetHashKey("apa_mp_apa_yacht_o3_rail_a")] = true,
            [GetHashKey("apa_mp_apa_yacht_o3_rail_b")] = true,
            [GetHashKey("apa_mp_apa_yacht_option1")] = true,
            [GetHashKey("proc_searock_01")] = true,
            [GetHashKey("apa_mp_h_yacht_")] = true,
            [GetHashKey("apa_mp_apa_yacht_option1_cola")] = true,
            [GetHashKey("apa_mp_apa_yacht_option2")] = true,
            [GetHashKey("apa_mp_apa_yacht_option2_cola")] = true,
            [GetHashKey("apa_mp_apa_yacht_option2_colb")] = true,
            [GetHashKey("apa_mp_apa_yacht_option3")] = true,
            [GetHashKey("apa_mp_apa_yacht_option3_cola")] = true,
            [GetHashKey("apa_mp_apa_yacht_option3_colb")] = true,
            [GetHashKey("apa_mp_apa_yacht_option3_colc")] = true,
            [GetHashKey("apa_mp_apa_yacht_option3_cold")] = true,
            [GetHashKey("apa_mp_apa_yacht_option3_cole")] = true,
            [GetHashKey("apa_mp_apa_yacht_jacuzzi_cam")] = true,
            [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple003")] = true,
            [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple1")] = true,
            [GetHashKey("apa_mp_apa_yacht_jacuzzi_ripple2")] = true,
            [GetHashKey("apa_mp_apa_yacht_radar_01a")] = true,
            [GetHashKey("apa_mp_apa_yacht_win")] = true,
            [GetHashKey("prop_crashed_heli")] = true,
            [GetHashKey("apa_mp_apa_yacht_door")] = true,
            [GetHashKey("prop_shamal_crash")] = true,
            [GetHashKey("xm_prop_x17_shamal_crash")] = true,
            [GetHashKey("apa_mp_apa_yacht_door2")] = true,
            [GetHashKey("apa_mp_apa_yacht")] = true,
            [GetHashKey("prop_flagpole_2b")] = true,
            [GetHashKey("prop_flagpole_2c")] = true,
            [GetHashKey("prop_flag_canada")] = true,
            [GetHashKey("apa_prop_yacht_float_1a")] = true,
            [GetHashKey("apa_prop_yacht_float_1b")] = true,
            [GetHashKey("apa_prop_yacht_glass_01")] = true,
            [GetHashKey("apa_prop_yacht_glass_02")] = true,
            [GetHashKey("apa_prop_yacht_glass_03")] = true,
            [GetHashKey("apa_prop_yacht_glass_04")] = true,
            [GetHashKey("apa_prop_yacht_glass_05")] = true,
            [GetHashKey("apa_prop_yacht_glass_06")] = true,
            [GetHashKey("apa_prop_yacht_glass_07")] = true,
            [GetHashKey("apa_prop_yacht_glass_08")] = true,
            [GetHashKey("apa_prop_yacht_glass_09")] = true,
            [GetHashKey("apa_prop_yacht_glass_10")] = true,
            [GetHashKey("prop_flag_canada_s")] = true,
            [GetHashKey("prop_flag_eu")] = true,
            [GetHashKey("prop_flag_eu_s")] = true,
            [GetHashKey("prop_target_blue_arrow")] = true,
            [GetHashKey("prop_target_orange_arrow")] = true,
            [GetHashKey("prop_target_purp_arrow")] = true,
            [GetHashKey("prop_target_red_arrow")] = true,
            [GetHashKey("apa_prop_flag_argentina")] = true,
            [GetHashKey("apa_prop_flag_australia")] = true,
            [GetHashKey("apa_prop_flag_austria")] = true,
            [GetHashKey("apa_prop_flag_belgium")] = true,
            [GetHashKey("apa_prop_flag_brazil")] = true,
            [GetHashKey("apa_prop_flag_canadat_yt")] = true,
            [GetHashKey("apa_prop_flag_china")] = true,
            [GetHashKey("apa_prop_flag_columbia")] = true,
            [GetHashKey("apa_prop_flag_croatia")] = true,
            [GetHashKey("apa_prop_flag_czechrep")] = true,
            [GetHashKey("apa_prop_flag_denmark")] = true,
            [GetHashKey("apa_prop_flag_england")] = true,
            [GetHashKey("apa_prop_flag_eu_yt")] = true,
            [GetHashKey("apa_prop_flag_finland")] = true,
            [GetHashKey("apa_prop_flag_france")] = true,
            [GetHashKey("apa_prop_flag_german_yt")] = true,
            [GetHashKey("apa_prop_flag_hungary")] = true,
            [GetHashKey("apa_prop_flag_ireland")] = true,
            [GetHashKey("apa_prop_flag_israel")] = true,
            [GetHashKey("apa_prop_flag_italy")] = true,
            [GetHashKey("apa_prop_flag_jamaica")] = true,
            [GetHashKey("apa_prop_flag_japan_yt")] = true,
            [GetHashKey("apa_prop_flag_canada_yt")] = true,
            [GetHashKey("apa_prop_flag_lstein")] = true,
            [GetHashKey("apa_prop_flag_malta")] = true,
            [GetHashKey("apa_prop_flag_mexico_yt")] = true,
            [GetHashKey("apa_prop_flag_netherlands")] = true,
            [GetHashKey("apa_prop_flag_newzealand")] = true,
            [GetHashKey("apa_prop_flag_nigeria")] = true,
            [GetHashKey("apa_prop_flag_norway")] = true,
            [GetHashKey("apa_prop_flag_palestine")] = true,
            [GetHashKey("apa_prop_flag_poland")] = true,
            [GetHashKey("apa_prop_flag_portugal")] = true,
            [GetHashKey("apa_prop_flag_puertorico")] = true,
            [GetHashKey("apa_prop_flag_russia_yt")] = true,
            [GetHashKey("apa_prop_flag_scotland_yt")] = true,
            [GetHashKey("apa_prop_flag_script")] = true,
            [GetHashKey("apa_prop_flag_slovakia")] = true,
            [GetHashKey("apa_prop_flag_slovenia")] = true,
            [GetHashKey("apa_prop_flag_southafrica")] = true,
            [GetHashKey("apa_prop_flag_southkorea")] = true,
            [GetHashKey("apa_prop_flag_spain")] = true,
            [GetHashKey("apa_prop_flag_sweden")] = true,
            [GetHashKey("apa_prop_flag_switzerland")] = true,
            [GetHashKey("apa_prop_flag_turkey")] = true,
            [GetHashKey("apa_prop_flag_uk_yt")] = true,
            [GetHashKey("apa_prop_flag_us_yt")] = true,
            [GetHashKey("apa_prop_flag_wales")] = true,
            [GetHashKey("prop_flag_uk")] = true,
            [GetHashKey("prop_flag_uk_s")] = true,
            [GetHashKey("prop_flag_us")] = true,
            [GetHashKey("prop_flag_usboat")] = true,
            [GetHashKey("prop_flag_us_r")] = true,
            [GetHashKey("prop_flag_us_s")] = true,
            [GetHashKey("prop_flag_france")] = true,
            [GetHashKey("prop_flag_france_s")] = true,
            [GetHashKey("prop_flag_german")] = true,
            [GetHashKey("prop_flag_german_s")] = true,
            [GetHashKey("prop_flag_ireland")] = true,
            [GetHashKey("prop_flag_ireland_s")] = true,
            [GetHashKey("prop_flag_japan")] = true,
            [GetHashKey("prop_flag_japan_s")] = true,
            [GetHashKey("prop_flag_ls")] = true,
            [GetHashKey("prop_flag_lsfd")] = true,
            [GetHashKey("prop_flag_lsfd_s")] = true,
            [GetHashKey("prop_flag_lsservices")] = true,
            [GetHashKey("prop_flag_lsservices_s")] = true,
            [GetHashKey("prop_flag_ls_s")] = true,
            [GetHashKey("prop_flag_mexico")] = true,
            [GetHashKey("prop_flag_mexico_s")] = true,
            [GetHashKey("prop_flag_russia")] = true,
            [GetHashKey("prop_flag_russia_s")] = true,
            [GetHashKey("prop_flag_s")] = true,
            [GetHashKey("prop_flag_sa")] = true,
            [GetHashKey("prop_flag_sapd")] = true,
            [GetHashKey("prop_flag_sapd_s")] = true,
            [GetHashKey("prop_flag_sa_s")] = true,
            [GetHashKey("prop_flag_scotland")] = true,
            [GetHashKey("prop_flag_scotland_s")] = true,
            [GetHashKey("prop_flag_sheriff")] = true,
            [GetHashKey("prop_flag_sheriff_s")] = true,
            [GetHashKey("prop_flag_uk")] = true,
            [GetHashKey("prop_flag_uk_s")] = true,
            [GetHashKey("prop_flag_us")] = true,
            [GetHashKey("prop_flag_usboat")] = true,
            [GetHashKey("prop_flag_us_r")] = true,
            [GetHashKey("prop_flag_us_s")] = true,
            [GetHashKey("prop_aircon_l_03")] = true,
            [GetHashKey("csx_coastsmalrock_05_")] = true,
            [GetHashKey("mp_player_int_rock")] = true,
            [GetHashKey("mp_player_introck")] = true,
            [GetHashKey("prop_flagpole_1a")] = true,
            [GetHashKey("prop_flagpole_2a")] = true,
            [GetHashKey("prop_flagpole_3a")] = true,
            [GetHashKey("prop_a4_pile_01")] = true,
            [GetHashKey("cs2_10_sea_rocks_lod")] = true,
            [GetHashKey("cs2_11_sea_marina_xr_rocks_03_lod")] = true,
            [GetHashKey("prop_gold_cont_01")] = true,
            [GetHashKey("prop_hydro_platform")] = true,
            [GetHashKey("ch3_04_viewplatform_slod")] = true,
            [GetHashKey("ch2_03c_rnchstones_lod")] = true,
            [GetHashKey("proc_mntn_stone01")] = true,
            [GetHashKey("prop_beachflag_le")] = true,
            [GetHashKey("proc_mntn_stone02")] = true,
            [GetHashKey("cs2_10_sea_shipwreck_lod")] = true,
            [GetHashKey("des_shipsink_02")] = true,
            [GetHashKey("prop_flag_japan_s")] = true,
            [GetHashKey("prop_flag_ls")] = true,
            [GetHashKey("prop_flag_lsfd")] = true,
            [GetHashKey("prop_flag_lsfd_s")] = true,
            [GetHashKey("prop_cable_hook_01")] = true,
            [GetHashKey("prop_flag_lsservices")] = true,
            [GetHashKey("prop_flag_lsservices_s")] = true,
            [GetHashKey("prop_flag_ls_s")] = true,
            [GetHashKey("prop_flag_mexico")] = true,
            [GetHashKey("prop_flag_mexico_s")] = true,
            [GetHashKey("csx_coastboulder_00")] = true,
            [GetHashKey("des_tankercrash_01")] = true,
            [GetHashKey("des_tankerexplosion_01")] = true,
            [GetHashKey("des_tankerexplosion_02")] = true,
            [GetHashKey("des_trailerparka_02")] = true,
            [GetHashKey("des_trailerparkb_02")] = true,
            [GetHashKey("prop_gold_vault_fence_l")] = true,
            [GetHashKey("prop_gold_vault_fence_r")] = true,
            [GetHashKey("prop_gold_vault_gate_01")] = true,
            [GetHashKey("prop_bank_vaultdoor")] = true,
            [GetHashKey("des_traincrash_root7")] = true,
            [GetHashKey("prop_flag_russia")] = true,
            [GetHashKey("prop_flag_russia_s")] = true,
            [GetHashKey("prop_flag_s")] = true,
            [GetHashKey("ch2_03c_props_rrlwindmill_lod")] = true,
            [GetHashKey("prop_flag_sa")] = true,
            [GetHashKey("prop_flag_sapd")] = true,
            [GetHashKey("prop_flag_sapd_s")] = true,
            [GetHashKey("prop_flag_sa_s")] = true,
            [GetHashKey("prop_flag_scotland")] = true,
            [GetHashKey("prop_flamingo")] = true,
            [GetHashKey("prop_asteroid_01")] = true,
            [GetHashKey("stt_prop_stunt_bowling_ball")] = true,
            [GetHashKey("stt_prop_stunt_bowling_pin")] = true,
            [GetHashKey("stt_prop_stunt_soccer_ball")] = true,
            [GetHashKey("stt_prop_stunt_soccer_lball")] = true,
            [GetHashKey("stt_prop_stunt_soccer_sball")] = true,
            [GetHashKey("stt_prop_stunt_tube_fn_01")] = true,
            [GetHashKey("stt_prop_stunt_tube_fn_02")] = true,
            [GetHashKey("stt_prop_stunt_tube_fn_03")] = true,
            [GetHashKey("stt_prop_stunt_tube_fn_04")] = true,
            [GetHashKey("stt_prop_stunt_tube_fn_05")] = true,
            [GetHashKey("stt_prop_stunt_domino")] = true,
            [GetHashKey("stt_prop_stunt_jump15")] = true,
            [GetHashKey("stt_prop_stunt_jump30")] = true,
            [GetHashKey("stt_prop_stunt_jump45")] = true,
            [GetHashKey("stt_prop_stunt_jump_l")] = true,
            [GetHashKey("stt_prop_stunt_jump_lb")] = true,
            [GetHashKey("stt_prop_stunt_jump_loop")] = true,
            [GetHashKey("stt_prop_stunt_jump_m")] = true,
            [GetHashKey("stt_prop_stunt_jump_mb")] = true,
            [GetHashKey("stt_prop_stunt_jump_s")] = true,
            [GetHashKey("stt_prop_stunt_jump_sb")] = true,
            [GetHashKey("stt_prop_stunt_landing_zone_01")] = true,
            [GetHashKey("stt_prop_stunt_ramp")] = true,
            [GetHashKey("stt_prop_stunt_target")] = true,
            [GetHashKey("stt_prop_stunt_target_small")] = true,
            [GetHashKey("stt_prop_stunt_target")] = true,
            [GetHashKey("stt_prop_stunt_track_bumps")] = true,
            [GetHashKey("stt_prop_stunt_track_cutout")] = true,
            [GetHashKey("stt_prop_stunt_track_dwlink")] = true,
            [GetHashKey("stt_prop_stunt_track_dwlink_02")] = true,
            [GetHashKey("stt_prop_stunt_track_dwsh15")] = true,
            [GetHashKey("stt_prop_stunt_track_dwshort")] = true,
            [GetHashKey("stt_prop_stunt_track_dwslope15")] = true,
            [GetHashKey("stt_prop_stunt_track_dwslope30")] = true,
            [GetHashKey("stt_prop_stunt_soccer_goal")] = true,
            [GetHashKey("stt_prop_stunt_tube_jmp2")] = true,
            [GetHashKey("stt_prop_track_stop_sign")] = true,
            [GetHashKey("stt_prop_race_gantry_01")] = true,
            [GetHashKey("stt_prop_race_start_line_01")] = true,
            [GetHashKey("stt_prop_race_start_line_01b")] = true,
            [GetHashKey("stt_prop_race_start_line_02")] = true,
            [GetHashKey("stt_prop_race_start_line_02b")] = true,
            [GetHashKey("stt_prop_race_start_line_03")] = true,
            [GetHashKey("stt_prop_race_start_line_03b")] = true,
            [GetHashKey("stt_prop_race_tannoy")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_m")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_mb")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_s")] = true,
            [GetHashKey("stt_prop_ramp_adj_flip_sb")] = true,
            [GetHashKey("stt_prop_ramp_adj_hloop")] = true,
            [GetHashKey("stt_prop_ramp_adj_loop")] = true,
            [GetHashKey("stt_prop_ramp_jump_l")] = true,
            [GetHashKey("stt_prop_ramp_jump_m")] = true,
            [GetHashKey("stt_prop_ramp_jump_s")] = true,
            [GetHashKey("stt_prop_ramp_jump_xl")] = true,
            [GetHashKey("stt_prop_ramp_jump_xs")] = true,
            [GetHashKey("stt_prop_ramp_jump_xxl")] = true,
            [GetHashKey("stt_prop_ramp_multi_loop_rb")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_l")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_m")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_s")] = true,
            [GetHashKey("stt_prop_ramp_spiral_l_xxl")] = true,
            [GetHashKey("stt_prop_ramp_spiral_m")] = true,
            [GetHashKey("stt_prop_ramp_spiral_s")] = true,
            [GetHashKey("stt_prop_ramp_spiral_xxl")] = true,
            [GetHashKey("p_crahsed_heli_s")] = true,
            [GetHashKey("prop_rock_4_big2")] = true,
            [GetHashKey("prop_beachflag_le")] = true,
            [GetHashKey("xs_prop_hamburgher_wl")] = true,
            [GetHashKey("prop_xmas_tree_int")] = true,
            [GetHashKey("sr_prop_spec_tube_xxs_01a")] = true,
            [GetHashKey("prop_ld_ferris_wheel")] = true,
            [GetHashKey("prop_const_fence02b")] = true,
            [GetHashKey("prop_container_05a")] = true, 
            [GetHashKey("prop_container_03b")] = true,
            [GetHashKey("prop_mp_ramp_03")] = true,
            [GetHashKey("ex_mapmarker_13_maze_bank_arena_1")] = true
        },
    },
};

exports("getConfig", function() return Config; end);