Citizen.CreateThread(function()
    AddTextEntry('rmodgt63', 'Mercedes-AMG GT 63 S')
    AddTextEntry('skyline', 'Nissan Skyline GT-R R34')
    AddTextEntry('16challenger', 'Dodge Challenger')
    AddTextEntry('370z', 'Nissan 370Z')
    AddTextEntry('aventador', 'Lamborghini Aventador')
    AddTextEntry('cz4a', 'Mitsubishi Lancer Evolution X')
    AddTextEntry('gtr', 'Nissan GTR')
    AddTextEntry('m3e46', 'BMW M3 E46')
    AddTextEntry('mgt', 'Ford Mustang GT')
    AddTextEntry('pts21', 'Porsche 911 Turbo S')
    AddTextEntry('rs7', 'Audi RS7')
    AddTextEntry('sim22', 'Subaru Impreza 22B-STi Series I')
    AddTextEntry('x6m', 'BMW X6M F16')
    AddTextEntry('rmodm4gts', 'BMW M4 GTS')
    AddTextEntry('raptor2017', 'Ford Raptor')
    AddTextEntry('r8ppi', 'Audi R8')
    AddTextEntry('i8', 'BMW i8')
    AddTextEntry('golfgti', 'Volkswagen Golf GTI V')
    AddTextEntry('g63', 'Mercedes AMG-G63')
    AddTextEntry('evoque', 'Range Rover Evoque')
    AddTextEntry('chevelle67', 'Chevrolet Chevelle Super Sport 396')
    AddTextEntry('cayenne18', 'Porsche Cayenne S')
    AddTextEntry('audisq7', 'Audi SQ7')
    AddTextEntry('rmodx6', 'BMW X6 f16')
end)