-- Citizen.CreateThread(function()
--     Wait(5000);
--     local shapes = getEntitiesByType("colshape");
--     iprint(shapes);

--     while (true) do 
--         for _, shape in ipairs(shapes) do 
--             DrawLine(x1, y1, z1, x2, y2, z2, red, green, blue, alpha);
--         end 
--     end 
-- end);